package org.openmolecules.chem.interaction.rf;

import com.actelion.research.chem.SortedStringList;
import com.actelion.research.chem.StereoMolecule;
import org.openmolecules.chem.interaction.AtomClassifier;

public class RFLigandAtomClassifier extends AtomClassifier {
	private static final String[][] LIGAND_TYPE = {
			{ "fHg`A?Ranj`", "P" },
			{ "fHfHAoW?Ranj`", "Br_any" },
			{ "fH@Nz?iPwUP", "C_sp2" },
			{ "fH@Ny?iPwUP", "C_sp3" },
			{ "fHdPAoW?Ranj`", "Cl_any" },
			{ "fHeXAoW?Ranj`", "I_any" },
			{ "fI@GU_iPwUP", "O_arom" },
			{ "fH`PAuWzTMuT", "S_arom" },
			{ "eFBCDcAuU~d`wUP", "Br_aryl" },
			{ "gCaHDIAIi`OIMJNmrO}Hd[jkjB@", "C_alkyl_polarized_aryl" },
			{ "fH@Njo[?Ranj`", "C_arom_ch" },
			{ "eFBBHcAuU~d`wUP", "Cl_aryl" },
			{ "eFBBPcAuS~d`wUP", "F_alkyl" },
			{ "eFBBPcAuU~d`wUP", "F_aryl" },
			{ "eFBBlcAuU~d`wUP", "I_aryl" },
			{ "eFHBJGe_iHMuT", "O_carbonyl" },
			{ "gGQHDIAInfhCjQjmhzwH{rY?RIFzjbmFz``", "C_alkyl_polarized_aryl_no_het" },
			{ "eMDARVCB_tdfzj{H", "C_carbonyl" },
			{ "diF`@@JfyIfYZjh@pHDsmIBMFAQ`xLiDeWhpfLpVJpvNqmDnV~DNalO}HRFzj{rXUMp`", "C_imine_nh" },
			{ "eF`BJGUNzmxw~ddwUP", "C_imine_no_h" },
			{ "gJT@LTiZhCBCRbfJrBD`TDIBjVMc}H`[jkjq@", "C_methylene_unpolarized" },
			{ "fH@M{wzTMuT", "C_no_h_buried" },
			{ "gC`@H{PFtTXhXOtbAnj`", "C_sp2_het_no_h" },
			{ "gC`@H{PG}H`[jh", "C_sp2_no_het_no_h" },
			{ "eFBBPcAuS^m?iHMuT", "F_cf" },
			{ "eMABPYAIhMz{~b`wURwUP", "F_cf2" },
			{ "gJX`DBdjt`XQQTQ`BLc@D_iDS]U@", "N_amide_acidic" },
			{ "gGX`DBdkMLAaEZVLlLGzQDwUWTJ", "N_amide_sec" },
			{ "dazL@DBnRVYZfPCZFcCPp_iBHwUW\\An@", "N_amide_tert_C_C" },
			{ "eF`BLFDZj?RP[jh", "N_aniline_prim" },
			{ "eMhDRVCjZ|}?RQ[jkjP", "N_arom_no_don_acc" },
			{ "eF`BNG}IAnj`", "N_nitrile" },
			{ "eMJH|Df`?iIMuT", "O_P_C_link" },
			{ "eMIH|GpRZC~ddwUP", "O_P_P_link" },
			{ "eFHBLFD[i?iHMuT", "O_alcohol_Csp3" },
			{ "eFhHcAkFotdFzjcD", "O_arom_isoxazole" },
			{ "eMHAIhLHuSZXsCAnk~d`wUWY@", "O_enol" },
			{ "eFHBLFDZj?RP[jh", "O_phenol" },
			{ "eFJH|HpXUVL_iIMuT", "O_phosph_on_ate_terminal" },
			{ "gJPhH`DQztAmM~dPMuT", "S_sulfonyl" },
			{ "gCaHH@bNtAoAw}H`[jh", "S_sulfoxide" },
			{ "gChHD@aIf`NiG}H`[jh", "S_thioamide" },
			{ "eMB@HchLHuC~d`wUP", "S_thioether" },
			{ "eFB@HcAaFj_tdFzj@", "S_thiol_alkyl" },
			{ "eFB@HcAaFjotdFzj@", "S_thiol_aryl" },
			{ "eM@H~C~d`wUP", "C_acetylene_no_h" },
			{ "eF@HxXU?DYRR[jh", "C_acetylene_polarized_ch" },
			{ "gNq`AVdlkTpFBSuB~c^JNLG`DMABPkKc}Hb[jkjE@", "C_alkyl_tertiary_polarized_C,S,P_O,F" },
			{ "eF`JLFMYpBDanG^N?iHMuT", "C_alkyl_tertiary_polarized_N,O,F" },
			{ "gNp@DjUjj@pHM_lWkmxxhHREPPdF`aHUvp\\WGzQ@wUW\\Zp", "C_alkyl_tertiary_unpolarized" },
			{ "gCh@@duPGTeWCTtmW`{~dRMuUFB@", "C_arom_c_no_h_c_n_no_don_acc" },
			{ "gC`@H}PGTEWCTtm_iDC]UQ``", "C_arom_c_no_h_c_n_no_don_acc" },
			{ "gCh@@duPFDfiKtEupuMKVxG~dRMuUrB`", "C_arom_c_no_h_n_don" },
			{ "gCa@@duPGQCIVjjZVotbQnj`", "C_arom_c_phen_ol_oxy" },
			{ "eM`AIhLJcNLG@HUSUj|]?RR[jjJU@", "C_arom_ch_shielded_polarized" },
			{ "eM@HzCBHrg@HUSUj}]?RP[jjJU@", "C_arom_ch_shielded_polarized" },
			{ "diE@@ByJyyZjd@pcHlBL@QF\\@`DEg@HRCHpAGYpBD`N\\@`DUHFIhm\\r|Iw}HSFzjbTJQUOVBB[a@", "C_arom_ch_shielded_unpolarized" },
			{ "gJX@@eZu@XSZ`XhHpADS`DJxLVmj|W_tbYnjhiV`", "C_arom_ch_shielded_weakly_polarized" },
			{ "gCh@DeMPFDdXlxABPjaiZoAw}Hd[jjJDh", "C_arom_ch_shielded_weakly_polarized" },
			{ "eM@HzCBHmcApBBg@HUSUj{[]?iHMuUEJ`", "C_arom_ch_unshielded_polarized" },
			{ "diF@@BRn^Vji@LLcA|dNKqXDX@bDxA@lxABPYF@H{N@PdAS`DJdCDtVnY]DwV?taL[jjKPiXeTl}XHInD", "C_arom_ch_unshielded_unpolarized" },
			{ "gJX`LDdru@_tbQnj`", "C_carbamate" },
			{ "gC``@dfZ@pPVyk~dRMuT", "C_carboxylate_Csp2" },
			{ "gC``@dfZ@pbwL?tbQnj`", "C_carboxylate_Csp3" },
			{ "eM@HvCBLq_iHMuT", "C_ethylene_ch" },
			{ "eF@HhXQ~d`wUP", "C_ethylene_ch2" },
			{ "gC`@H{PGLE~dPMuT", "C_ethylene_no_h" },
			{ "eM@HzCAguOELXO@HdDIBlX?RQ[jh", "C_methyl_polarized_C,S,P_O,F" },
			{ "eF`JLFDQkN@PdOtdFzj@", "C_methyl_polarized_N,O,F" },
			{ "eF@HpXQjk}IAnj`", "C_methyl_polarized_aryl" },
			{ "eM@HzCAgTOj^MHHREXq~dbwUWZ@", "C_methyl_unpolarized" },
			{ "eM@HzCBMS[i?iHMuT", "C_methylene_alkyl_aryl" },
			{ "eM@HzCBMMM~d`wUP", "C_methylene_aryl_aryl" },
			{ "gJP`@TeVhCBKRcgtKqVq`|@`hHREYl_iDS]U]`@", "C_methylene_polarized_C,S,P_O,F" },
			{ "eF`JLFMYpBDanG^M?iHMuT", "C_methylene_polarized_N,O,F" },
			{ "eF`BNG}IInj`", "C_nitrile" },
			{ "gC`@H}PFFbwHOtbAnj`", "C_tbut" },
			{ "gChHD@aIf`OzQHwUP", "C_thioamide" },
			{ "gC`LAHJPt`duPG}L`[jiMuUfzj@", "F_cf3" },
			{ "gGX`DBdkMLAaEjQ?RHfzj{A^ZB", "N_amide_acyclic_sec" },
			{ "dazL@DBnRVYZfPCiHR_taD[jkjAuxrB", "N_amide_acyclic_tert" },
			{ "dazL@DBnRVYZfPCUHddotaD[jkjAuxq|", "N_amide_cyclic_tert" },
			{ "gCi@DDfZ@pbwM_tbInj`", "N_amide_prim_Csp2" },
			{ "gCi@DDfZ@pbwL?tbInj`", "N_amide_prim_Csp3" },
			{ "gJX`AbeKR`XPZTTqVs`D@`ypB@Q~dPMuUuXw```", "N_amine_acyclic_sec" },
			{ "gNy`@ZtjUjU@p`uhisGGN@PBKg@HACs`D@c}H`[jknM]xHH", "N_amine_acyclic_tert" },
			{ "gJX`AbeKR`XPZpXibmg@HAAs`D@c}H`[jkjqo@~@", "N_amine_cyclic_sec" },
			{ "gNy`@ZtjUjU@p`uhisGGN@PBKg@HACs`D@c}H`[jknM]xGp", "N_amine_cyclic_tert" },
			{ "eMhARYCBMTqgN@PBOtdFzj{H", "N_amine_prim" },
			{ "gJXA@IczhC~dPMuT", "N_ammonium_ion" },
			{ "gCi@Adii@p`t`jcMg@HAFyK~dPMuUvX", "N_aniline_sec_Csp2" },
			{ "eM`BN`pcRK[i?iHMuT", "N_aniline_sec_Csp3" },
			{ "gJY@@TjZdCkAUjLN\\@`D_iDC]U]a@", "N_aniline_tert_Csp2_Csp2" },
			{ "gGX`@ZeRuJAaAkQSjJN\\@`DWN@PBOtbAnjnht", "N_aniline_tert_Csp3_Csp3" },
			{ "diF`@@JfyIfYZjh@pHDsmIBMFAQ`xLiDeWhpfLpVJpvNqmDnV~DNalO}HPFzj{rXUMp`", "N_imine_nh" },
			{ "gCh@@eLhGTSF[N@PBKp[?RHFzjzi`", "N_imine_no_h" },
			{ "fJ@GU_iPwUWKW``", "N_pyridinium" },
			{ "gChHD@aIf`OzQDwUP", "N_thioamide" },
			{ "eMHAIhLDotdFzj@", "O_alcohol_Csp3_primary" },
			{ "gCa@@duPFBD?RHFzj@", "O_alcohol_Csp3_secondary" },
			{ "gJQ@@duU@XP_iDC]U@", "O_alcohol_Csp3_tertiary" },
			{ "eMhDRYC~d`wUTTj@", "O_arom_oxazole" },
			{ "gJX`LDdru@_tbAnj`", "O_db_carbamate" },
			{ "gCh`HDduPFBBjabX?QHFzjS]U@", "O_nitro" },
			{ "gCi@HDfj@p`uHvbcECAVSGzQ@wUWX`", "O_oh_hydroxylamin" },
			{ "gJX`LDdru@_tbInj`", "O_sb_carbamate" },
			{ "gC`D@DPHRfhCAB_hdC]UQnj`", "S_disulfide" },
			{ "gJXhMD@bOV`OzQ@wUP", "S_sulfonamide" },
			{ "gJPhH`DQztA?RHFzj@", "S_sulfone" },
			{ "gCi@DDfZ@pbwM_tbQnj`", "C_amide_prim_Csp2" },
			{ "gCi@DDfZ@pbwL?tbQnj`", "C_amide_prim_Csp3" },
			{ "gJY@DDfVhCBKZuM?RIFzj@", "C_amide_sec_Csp2_Csp2" },
			{ "gJY@DDfVhCBKZuK?RIFzj@", "C_amide_sec_Csp2_Csp3" },
			{ "gJY@DDfVhCBKZsM?RIFzj@", "C_amide_sec_Csp3_Csp2" },
			{ "gJY@DDfVhCBKZsK?RIFzj@", "C_amide_sec_Csp3_Csp3" },
			{ "gGY@DDfYj`OzQHwUP", "C_amide_tert_C_C" },
			{ "gCh@@duPGTEfIkajZVmpW~HLiDc]UQPi@", "C_arom_c_no_h_n_acc_bridge" },
			{ "gCh@@duPGTEfJjajZwA_x`rdRMuUEBd", "C_arom_c_no_h_n_acc_no_bridge" },
			{ "gCh@@dmPFDeilqUTMSUtMkozQHwUTTJP", "C_arom_ch_shielded_no_bridge_polarized_acc" },
			{ "diD`@LKarRIFJjj`CBDtPTJSLRsN@PdBs`DIClxABPGN@PdLieuUHtVkpG_taD[jjJQE]ZLInD", "C_arom_ch_shielded_unpolarized_no_chelating" },
			{ "gJP`@dfVhCmZf?iDc]UWb``", "C_ester_acyclic_Csp2_Csp2" },
			{ "gJP`@dfVhCmZe?iDc]UWb``", "C_ester_acyclic_Csp2_Csp3" },
			{ "gJP`@dfVhCmYf?iDc]UWb``", "C_ester_acyclic_Csp3_Csp2" },
			{ "gJP`@dfVhCmYe?iDc]UWb``", "C_ester_acyclic_Csp3_Csp3" },
			{ "gGU@DPdkMTAuLvebhc@DUFC`kecXNMsVzPrO}Hf[jklh", "C_guan_amid_inium_polarized" },
			{ "gGU@CPdkMTAuLqTQ`BDcApUrqlGFyk]D]G~dSMuT", "C_guan_amid_inium_polarized" },
			{ "dkML@DhMMIYkgvjjiPCkLRikDS]LRaF@HyFC`EF@HUF@HjrXsAXkCXGFxrwQAtO}HSFzjzhPS\\Lki`", "C_guan_amid_inium_unpolarized" },
			{ "gJX`DBdru@XIG}Hd[jh", "C_hydroxamate" },
			{ "gCa@@dsPGZUu?RIFzj@", "C_ketone_Csp2_Csp2" },
			{ "gCa@@dsPGZSu?RIFzj@", "C_ketone_Csp3_Csp2" },
			{ "gCa@@dsPGZSs?RIFzj@", "C_ketone_Csp3_Csp3" },
			{ "eMHBN`pkTwzRS]U@", "C_methoxy_arom" },
			{ "eF`BLFE_iIMuUrL", "C_methyl_polarized_ammonium" },
			{ "gGX@KddQjhCBSTKFWN@PdJjZVotbQnjhjRnr`", "C_methylen_polarized_aryl_no_het" },
			{ "gJT@LTiZhCBCRbfJv\\@aHGN@PdJi\\wOtbAnjnkF|DD", "C_methylene_unpolarized_acyclic" },
			{ "gJT@LTiZhCBCRbfJv\\@aHGN@PdJi\\wOtbAnjnkF|Cx", "C_methylene_unpolarized_cyclic" },
			{ "gCe@E`dsPFDVig}Hd[jh", "C_urea_prim" },
			{ "gJU@E`dru@XQ\\fuL{aozQHwUP", "C_urea_sec_Csp2" },
			{ "gGU@E`drmTAaMjIvcJ{q[?RIFzj{B", "C_urea_sec_Csp3" },
			{ "gNu@E`dsKUPGdvig\\]?RIFzj{F", "C_urea_tert" },
			{ "eF`BLGRUVktW^n?iHMuUFH", "N_arom_donor_shielded" },
			{ "eM`BN`pcVUMYg\\N{[]?iHMuT", "N_arom_donor_unshielded" },
			{ "gGU@DPdkMTAaCjIcHc@DUrqlGFyk~dPmuT", "N_guan_amid_inium_prim_polarized" },
			{ "gGU@CPdkMTAaCjUbhc@DIFC`kecXNMsW}Ha[jh", "N_guan_amid_inium_prim_polarized" },
			{ "gGU@DPdkMTAyCiIKFQF@HkecXNMsW}Ha[jh", "N_guan_amid_inium_sec_polarized" },
			{ "gGU@CPdkMTAyCiEkEQF@HRLGAWKFp\\[fozQBwUP", "N_guan_amid_inium_sec_polarized" },
			{ "gCi@DDfZ@pbwM_tbAnj`", "O_amide_prim_Csp2" },
			{ "gCi@DDfZ@pbwL?tbAnj`", "O_amide_prim_Csp3" },
			{ "gJY@DDfVhCBK}H`[jj|TD", "O_amide_sec_acyclic" },
			{ "gGY@DDfYj`OzQ@wUWHj", "O_amide_tert_C_C" },
			{ "gJX`DBdru@XIG}H`[jh", "O_db_hydroxamate" },
			{ "gJQ`@bdjt`]jSS}Hb[jkjAoEA@", "O_ether_acyclic_Csp2_Csp2" },
			{ "gJQ`@bdjt`]jOS}Hb[jkjAoEA@", "O_ether_acyclic_Csp3_Csp2" },
			{ "eMHBN`{Yk?RP[jj|PP", "O_ether_acyclic_Csp3_Csp3" },
			{ "eMHBN`{Yk?RP[jj|O`", "O_ether_cyclic" },
			{ "gJY@HDfZdCrCTcZZJtLAS`DOtbAnjns@", "O_no_h_hydroxyl-amdine_amid" },
			{ "gNy@HDfeje@|`uHvaccCATxAAipBGzQ@wUWRcV", "O_no_h_hydroxylamin" },
			{ "gJU@HPdsT`XPZd[SQfa`kEc}H`[jklp", "O_oh_hydroxyl-amidine" },
			{ "gJX`DBdru@XIG}Ha[jh", "O_sb_hydroxamate" },
			{ "gJXhMD@bOV`MhXppp_hdc]UInj`", "O_sulf_on_amide" },
			{ "gJPhH`DQztAmMFZFC}Dd[jiMuT", "O_sulfonyl" },
			{ "gCaHH@bNtAoAw}Hd[jh", "O_sulfoxide" },
			{ "gJQhHl@bOV`LIotbAnj`", "S_sulfonate" },
			{ "gKXHL@aJWFe`OzQ@wUP", "S_thiazole" },
			{ "gKPH@DIRxtlA?RHFzj@", "S_thiophene" },
			{ "gCh@@duPGTEzJLrUTMKVxK?DFTbQnjhhR`", "C_arom_c_no_h_n_acc_methyl_en" },
			{ "gFp@DiTt@@CCBK}H`[jh", "C_arom_phenyl" },
			{ "gFt@ATiTt@@CBS}Hd[jh", "C_arom_pyrazine" },
			{ "gJT@LTiZhCBCRbfJv\\@aHGN@PdJi\\wOtbAnjnkF|Cx", "C_methylene_unpolarized_cyclic_no_heterocycle" },
			{ "gFt@ADiTt@@CBK}Hb[jh", "C_pyridazine" },
			{ "gFx@@eJf`@@[z[V}o}Hd[jh", "C_pyridine_2" },
			{ "gFx@@eJf`@@XZZ?iDs]U@", "C_pyridine_3" },
			{ "gFx@@eJf`@@X[F?iDk]U@", "C_pyridine_4" },
			{ "gFt@AdiTt@@CBS}Hd[jh", "C_pyrimidine_2" },
			{ "gFt@@TiTt@@CCBG}Hd[jh", "C_pyrimidine_4" },
			{ "gFt@AdiTt@@CCCG}Ha[jh", "C_pyrimidine_5" },
			{ "gGX`DBdkMLAaEmRv?iDS]U]`oEA@", "N_amide_sec_acyclic_Csp2_Csp2" },
			{ "gJY@DDfVhCBKZuK?RHfzjoEA@", "N_amide_sec_acyclic_Csp2_Csp3" },
			{ "gGX`DBdkMLAaEmRu?iDS]U]`oEA@", "N_amide_sec_acyclic_Csp3_Csp2" },
			{ "gJY@DDfVhCBKZsK?RHfzjoEA@", "N_amide_sec_acyclic_Csp3_Csp3" },
			{ "gGX`DBdkMLAaEjIvi[_tbInjnpWb_@", "N_amide_sec_cyclic_Csp2_Csp2" },
			{ "gJY@DDfVhCBKTSmZe?iDS]UWb_@", "N_amide_sec_cyclic_Csp2_Csp3" },
			{ "gGX`DBdkMLAaEmRu?iDS]U]`oD~@", "N_amide_sec_cyclic_Csp3_Csp2" },
			{ "gJY@DDfVhCBKZsK?RHfzjoD~@", "N_amide_sec_cyclic_Csp3_Csp3" },
			{ "gCd@Adij@vb}ME\\MSRumBrwPvn?iDC]U\\`lYH", "N_arom_acceptor_shielded_CNH" },
			{ "eMPARZCzXjfkVtm[in{~d`wUWHlX`", "N_arom_acceptor_shielded_CNH" },
			{ "gJ\\@AbeKU@_KPXjQjZVMkZEenam]?RHFzjyAXrW]LP", "N_arom_acceptor_shielded_no_CNH" },
			{ "gCd@Adij@vb}MDXhXJxZfecZEenam]?RHFzjyAXrWUL", "N_arom_acceptor_shielded_no_CNH" },
			{ "eM`BN`pbsMTuZwEnvw_zRC]U\\bqRh", "N_arom_acceptor_unshielded" },
			{ "gNr@ALtkmjj@p`ueY[zRzdZfmhzwA[r[?RIFzjxaYXdTmFz\\Zp", "N_arom_donor_n_acc" },
			{ "dayD@DHNRUmZjPCBBtbNL\\aF@HiFC`YF@HkbXsAXwFW}HPfzjzPPw@", "N_guan_amid_inium_prim_unpolarized" },
			{ "deeL@DHAeIVUVjiPCrDubNILRaF@HiFC`YF@HyF@HkbXsAXwFW}HQFzjzpPwCH", "N_guan_amid_inium_sec_unpolarized" },
			{ "gNxhMD@cIICEj`OzQLwUP", "N_nc2_sulfonamide" },
			{ "gJXhMD@bOV`LIotbYnj`", "N_nh2_sulfonamide" },
			{ "gGXhMD@cIIBmPFDwzQLwUP", "N_nhc_sulfonamide" },
			{ "gCe@E`dsPFDVifLr\\@a~dQMuT", "N_urea_carbamate_prim" },
			{ "gJU@E`dru@XQZfXsIpBFx[~dQMuT", "N_urea_carbamate_sec_Csp2" },
			{ "gJU@E`dru@XQZfXsIpBFxW~dQMuT", "N_urea_carbamate_sec_Csp3" },
			{ "gJU@E`dru@XQZf[PqVS`DCCAnF?iDS]U@", "N_urea_carbamate_sec_Nsp2" },
			{ "gJU@E`dru@XQZf[PqVS`DCCAnE?iDS]U@", "N_urea_carbamate_sec_Nsp3" },
			{ "gGU@E`dsMTAuLqfS`DOtbInj`", "N_urea_carbamate_tert" },
			{ "gGU@E`dsMTAuLvQlUdxA@pp_iDS]U@", "N_urea_carbamate_tert_N" },
			{ "gC``@dfj@pPUTLSFuKk~bPMuTfzj@", "O_carboxylate_Csp2" },
			{ "gC``@dfj@pPUTLSFuKg~bPMuTfzj@", "O_carboxylate_Csp3" },
			{ "gCa@@dsPGZUu?RHFzj@", "O_ketone_Csp2_Csp2" },
			{ "gCa@@dsPGZSu?RHFzj@", "O_ketone_Csp3_Csp2" },
			{ "gCa@@dsPGZSs?RHFzj@", "O_ketone_Csp3_Csp3" },
			{ "gJP`@dfVhCgQSg\\K?RHFzj@", "O_lactone" },
			{ "gJXhMD@bOV`OzIHwUR[jh", "O_sulfonamide" },
			{ "gJQhHl@bOV`LIotrQnjdwUV[jh", "O_sulfonate" },
			{ "gJPhH`DQztA?QIFzjS]U@", "O_sulfone" },
			{ "gCe@E`dsPFDVig}H`[jh", "O_urea_prim" },
			{ "gJU@E`dru@XQ\\fuL{aozQ@wUP", "O_urea_sec_Csp2" },
			{ "gGU@E`drmTAaMjIvcJ{q[?RHFzj{B", "O_urea_sec_Csp3" },
			{ "gNu@E`dsKUPGdvig\\]?RHFzj{F", "O_urea_tert" },
			{ "gCd@@dfj@qfQ`xJxZfekZCe?RIFzjcI@", "C_arom_amidine_three_neighbours" },
			{ "eO@HyjCAf|]?QR[ji[jh", "C_cpro_ext" },
			{ "eO@HyjCAf|]?RP[jh", "C_cpro_int" },
			{ "gJT@LTiZhCBCRbfJv\\@aHGN@PdJi\\wOtbAnjnkF|Ax", "C_methylene_unpolarized_cyclic_no_heterocycle_cycpro" },
			{ "gNr@ALtkmjj@p`tlm}I]]M[Qu^S_|RYRHFzjyAXdTmFz\\Zp", "N_arom_acceptor_n_don" },
			{ "daED@DpNRYUifjV@LHSZH|_zPbMuUqDnT", "N_donor_pyridone" },
			{ "gOy@DDfUkZe`LHoQWnI?iDS]U\\bh", "N_donor_pyridone" },
			{ "daED@DpFRYVkfjY@LDSMhcq?iBHwUWDRyP", "N_donor_uracil" },
			{ "gJX`DBdru@XIG}Hb[jh", "N_hydroxamate" },
			{ "gKT@@Ti\\YZ@pd?RHFzjyAP", "N_imidazole_acceptor_unshielded" },
			{ "eMPBchLJuC~ddwUP", "N_nh2_ext_hydrazine" },
			{ "gJT@ADiZdCBCRCFLN\\@`D_iDC]U]a@", "N_nh_hydrazine" },
			{ "gCe@I`dmHFBDuH?iDc]U@", "N_nh_hydroxyl_amidine" },
			{ "gCi@HDei@pPfiFLr\\@a~dRMuUvX", "N_nh_hydroxylamin" },
			{ "gCh`HDduPFBBjabX?RIFzj@", "N_nitro" },
			{ "gNt@ADjUje@zPXqUs`D@aypB@Q~dPMuUuU`", "N_no_h_hydrazine" },
			{ "gJY@HDfZdCABZdXpipBGzQHwUP", "N_no_h_hydroxyl_amdine_amid" },
			{ "gGY@HDfViPLDIjQbbg@HUN@P?RIFzjzcP", "N_no_h_hydroxylamin" },
			{ "gFt@ATiTt@@CAQ_iDC]U@", "N_pyrazine" },
			{ "gFx@@eJf`@@XJK}H`[jkdE@", "N_pyridine" },
			{ "gFt@AdiTt@@CBS}D`[jkMuT", "N_pyrimidine" },
			{ "gJY@DDfVhCBKZuM?RHFzjoEA@", "O_amide_sec_acyclic_Csp2_Csp2" },
			{ "gJY@DDfVhCBKZuK?RHFzjoEA@", "O_amide_sec_acyclic_Csp2_Csp3" },
			{ "gJY@DDfVhCBKZsM?RHFzjoEA@", "O_amide_sec_acyclic_Csp3_Csp2" },
			{ "gJY@DDfVhCBKZsK?RHFzjoEA@", "O_amide_sec_acyclic_Csp3_Csp3" },
			{ "gJY@DDfVhCBKZuM?RHFzjoD~@", "O_amide_sec_cyclic_Csp2_Csp2" },
			{ "gJY@DDfVhCBKZuK?RHFzjoD~@", "O_amide_sec_cyclic_Csp2_Csp3" },
			{ "gJY@DDfVhCBKZsM?RHFzjoD~@", "O_amide_sec_cyclic_Csp3_Csp2" },
			{ "gJY@DDfVhCBKZsK?RHFzjoD~@", "O_amide_sec_cyclic_Csp3_Csp3" },
			{ "gJX`BDdwU@XHJLJ\\@aWCDqn[TnozI@wUR[jklH", "O_carboxylate_Csp2_not_N,O" },
			{ "gJX`BDdwU@XHJLJ\\@aUCDqmRy?hdC]UInjnp`", "O_carboxylate_Csp3_not_N,O" },
			{ "gJP`@dfVhCmZf?iDC]UWb``", "O_db_ester_acyclic_Csp2_Csp2" },
			{ "gJP`@dfVhCmZe?iDC]UWb``", "O_db_ester_acyclic_Csp2_Csp3" },
			{ "gJP`@dfVhCmYf?iDC]UWb``", "O_db_ester_acyclic_Csp3_Csp2" },
			{ "gJP`@dfVhCmYe?iDC]UWb``", "O_db_ester_acyclic_Csp3_Csp3" },
			{ "gJP`@dfVhCmZf?iDS]UWb``", "O_sb_ester_acyclic_Csp2_Csp2" },
			{ "gJP`@dfVhCmZe?iDS]UWb``", "O_sb_ester_acyclic_Csp2_Csp3" },
			{ "gJP`@dfVhCmYf?iDS]UWb``", "O_sb_ester_acyclic_Csp3_Csp2" },
			{ "gJP`@dfVhCmYe?iDS]UWb``", "O_sb_ester_acyclic_Csp3_Csp3" },
			{ "gKT@@Ti\\YZ@|d?RHFzjyAP", "N_imidazole_acceptor_shielded" },
			{ "gGT@ADjviPLIMPLT\\xA@Hn\\@`D_iDC]U]rM@", "N_nh_int_hydrazine" },
			{ "dieH@DHDeYWaZ@@@NhQcDHpAGzPaMuUrBoTB@", "N_pyridine_ortho_amino" },
			{ "digH@DHPRUe^Eh@@@pamPcFHQ`BOtQB[jhVzjz`P", "N_pyrimidine_amino" },
			{ "gKR@AEdi\\Zj@uhuMKVt]Wa{~bPMuUFzjcQRUhp", "N_tetrazole_ext" },
			{ "gKR@AEdi\\Zj@uhuMKVt]Wa{~bQMuUfzjcQRUhp", "N_tetrazole_int" },
			{ "gK\\@ALeKcMHFDg|RYQHFzjs]U@", "N_triazole_acceptor" },
			{ "gK\\@ALeKcMHFDgzQHwUP", "N_triazole_donor" },
			{ "dk^@@@RfV^tjFZAHJh@Mby]NI\\g@HJg@HZg@HFg@H_iBHwUWRy]L", "C_arom_indole_2" },
			{ "dk^@@@RfV^tjFZAHJh@Mby]NI\\g@HJg@HZg@HFg@H_iBTwUWRy]L", "C_arom_indole_3" },
			{ "dk^@@@RfV^tjFZAHJh@Mby]NI\\g@HJg@HZg@HFg@H_iBBwUWRy]L", "C_arom_indole_5" },
			{ "dk^@@@RfV^tjFZAHJh@Mby]NI\\g@HJg@HZg@HFg@H_iBRwUWRy]L", "C_arom_indole_6" },
			{ "dk^@@@RfV^tjFZAHJh@Mby]NI\\g@HJg@HZg@HFg@H_iBLwUWRy]L", "C_arom_indole_7" },
			{ "dk^@@@RfV^tjFZAHJh@Mby]NI\\g@HJg@HZg@HFg@H_iBXwUWRy]L", "C_arom_indole_a" },
			{ "dk^@@@RfV^tjFZAHJh@Mby]NI\\g@HJg@HZg@HFg@H_iB@wUWRy]L", "N_indole" },
			{ "dieH@DDDeYWaZ@@@NhQcDHpAGzP`muUrAoTB@", "N_pyridine_para_amino" },
			{ "dk^@@@RfV^tjFZAHJh@Mby]NI\\g@HJg@HZg@HFg@H_iBDwUWRy]L", "C_arom_indole_4" },
			{ "dk^@@@RfV^tjFZAHJh@Mby]NI\\g@HJg@HZg@HFg@H_iBPwUWRy]L", "C_arom_indole_b" },
	};

	private static volatile RFLigandAtomClassifier sDefaultInstance;
	private static volatile SortedStringList sTypeNameList;
	private static volatile StereoMolecule[] sFragment;
	private static volatile int[][] sFlaggedAtom;

	/**
	 * @return not threadsafe default instance of this class
	 */
	public static RFLigandAtomClassifier getDefaultInstance() {
		if (sDefaultInstance == null)
			sDefaultInstance = new RFLigandAtomClassifier();

		return sDefaultInstance;
	}

	public RFLigandAtomClassifier() {
		if (sTypeNameList == null) {
			synchronized (RFLigandAtomClassifier.class) {
				if (sTypeNameList == null) {
					sTypeNameList = new SortedStringList();
					for (String[] idcodeAndTypeName : LIGAND_TYPE)
						sTypeNameList.addString(idcodeAndTypeName[1]);

					sFragment = new StereoMolecule[LIGAND_TYPE.length];
					sFlaggedAtom = new int[LIGAND_TYPE.length][];

					initializeStaticStuff(LIGAND_TYPE, sFragment, sFlaggedAtom);
				}
			}
		}
		initialize(sFragment, sFlaggedAtom);
	}

	@Override
	public int getAtomTypeIndex(String typeName) {
		return (typeName == null || typeName.equals("?")) ? 0 : 1+sTypeNameList.getListIndex(typeName);
	}

	@Override
	public String getAtomTypeName(int type) {
		return type == TYPE_UNKNOWN ? "?" : sTypeNameList.getStringAt(type-1);
	}
}
